- name: Create a rhdg-{{ env }} project
  community.okd.k8s:
    host: "{{ ocp_url | mandatory }}"
    api_key: "{{ openshift_auth_results['openshift_auth']['api_key'] | mandatory }}"
    validate_certs: "{{ validate_certs }}"
    name: "{{ cluster_namespace }}"
    api_version: v1
    kind: Namespace
    state: "{{ rhdg_cluster_state }}"

- name: Process the rhdg cluster template file and create the resources
  community.okd.openshift_process:
    host: "{{ ocp_url | mandatory }}"
    api_key: "{{ openshift_auth_results['openshift_auth']['api_key'] | mandatory }}"
    validate_certs: "{{ validate_certs }}"
    parameters:
      CLUSTER_NAMESPACE: "{{ cluster_namespace }}"
      CLUSTER_NAME: "{{ cluster_name }}"
      EXTRA_JVM_OPTS: "{{ extra_jvm_opts }}"
    src: ./roles/rhdg_cluster/files/rhdg-cluster.yaml # The default role path doesn't work.
    state: "{{ rhdg_cluster_state }}"
