apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhdg8-operator
  annotations:
    description: Template to deploy a RHDG operator on OCP.
    tags: infinispan,datagrid,operator
    iconClass: icon-datagrid
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: datagrid-operator
    namespace: ${OPERATOR_NAMESPACE}
  spec:
    channel: 8.3.x
    installPlanApproval: ${PLAN_APPROVAL} 
    name: datagrid
    source: redhat-operators
    sourceNamespace: openshift-marketplace
parameters:
- name: OPERATOR_NAMESPACE
  description: "The project where the operator will be installed."
  required: false
  value: "openshift-operators"
- name: PLAN_APPROVAL
  description: "Define if the install plan requires approval."
  required: false
  value: "Manual"
