apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhdg8-cluster
  annotations:
    description: Template to deploy a RHDG cluster on OCP.
    tags: infinispan,datagrid,operator
    iconClass: icon-datagrid
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:

- apiVersion: infinispan.org/v1
  kind: Infinispan
  metadata:
    name: ${CLUSTER_NAME}
    namespace: ${CLUSTER_NAMESPACE}
    annotations:
      infinispan.org/monitoring: 'false'
    labels:
      type: middleware
      prometheus_domain: ${CLUSTER_NAME}
  spec:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app: infinispan-pod
                clusterName: ${CLUSTER_NAME}
                infinispan_cr: ${CLUSTER_NAME}
            topologyKey: kubernetes.io/hostname
          weight: 100
    container:
      cpu: "2:1"
      memory: "4G:2G"
      extraJvmOpts: ${EXTRA_JVM_OPTS}
    expose:
      type: Route
    logging:
      categories: {}
    replicas: 3
    security:
      endpointAuthentication: false
      endpointEncryption:
        type: None
    service:
      container:
        ephemeralStorage: true
        storage: 1Gi
        # storageClassName: ocs-storagecluster-cephfs
      type: DataGrid
    
parameters:
- name: CLUSTER_NAMESPACE
  description: "The project where the RHDG cluster will be installed."
  required: false
  value: "rhdg"
- name: CLUSTER_NAME
  description: "The name of the RHDG cluster."
  required: false
  value: "rhdg"
- name: EXTRA_JVM_OPTS
  required: false
  value: "-Xlog:gc*=info:file=/tmp/gc.log:time,level,tags,uptimemillis:filecount=10,filesize=1m -XX:-UseParallelOldGC -XX:+UseG1GC -XX:MaxGCPauseMillis=400"
